### ISSUE TITLE
data download too slow...

### ISSUE THREAD

**Issue by Tomzxcv** [darglein/ADOP#12]
Have other download link？

**Comment by darglein** [comment]
I just tested the download and it works as expected.

![image](https://user-images.githubusercontent.com/16142878/140272093-4c24426f-546c-46e6-a472-24143e3a3e58.png)

**Comment by Tomzxcv** [comment]
![111](https://user-images.githubusercontent.com/20981005/140272819-d18f152a-d5fc-4bdc-a774-2a43425da994.png)

but only 4KB/s in my computer

**Comment by darglein** [comment]
Can you verify on a different computer and different internet connection that this is an actual problem with the host?

**Comment by Tomzxcv** [comment]
i try it on other computer
