### ISSUE TITLE
How to generate a video from a given trajectory?

### ISSUE THREAD

**Issue by vahidEttehadi** [darglein/ADOP#16]
Hi, I saw you provided some videos for the trained models on the different scenes. I was wondering how you generated them? Is it possible to generate them with the viewer?

**Comment by darglein** [comment]
Yes all the videos in the supplementary material were generated by the viewer.

To make that work you currently have to install the ffmpeg dev packages to your system. Once you have installed them check in the cmake output if ffmpeg was found correctly. On my system it displays the following line:

`-- Package FFMPEG                     Yes, at /usr/include/x86_64-linux-gnu`

After that recompile everything and you find an additional GUI tab about video recording.

**Comment by vahidEttehadi** [comment]
Thanks! Now I can see the video recording options.

**Comment by cduguet** [comment]
I unfortuntately cannot compile with ffmpeg in Ubuntu 18.04, not even the oldest ffmpeg version (3.4.2). It seems that saiga uses ffmpeg API calls which are [deprecated as of 3.1.5](https://ffmpeg.org/pipermail/libav-user/2016-October/009801.html)? 

Which OS are you using?

**Comment by zuixiaosanlang** [comment]
@cduguet 
hi, 
have you solved the problem in Ubuntu 18.04 ??
