### ISSUE TITLE
Train on other dataset.

### ISSUE THREAD

**Issue by Sylvia6** [darglein/ADOP#18]
Thank you for the great project.
When I run adop_train with other data processed in adop data format,  I get an error showing that (Note that my image data is PNG file format):
```
libpng error: Not a PNG file
```
Can anyone help me with this issue?
![image](https://user-images.githubusercontent.com/32163681/141058867-a930f4d9-4e77-4ee5-bbf5-47935bc2f404.png)

**Comment by darglein** [comment]
What is the output of `identify` on one of your images?

```
identify scenes/gfcs/img/xxx.png
```

**Comment by Sylvia6** [comment]
@darglein  Thanks, it is the problem of my image  format
