### ISSUE TITLE
Mention nvidia-cuda-toolkit as a dependency in compilation instructions

### ISSUE THREAD

**Issue by Schwusch** [darglein/ADOP#20]
As the title says, not everyone has that dependency installed and will receive this error during compilation:
```
Could not find nvcc, please set CUDAToolkit_ROOT.
```

**Comment by Schwusch** [comment]
Oh nevermind, it's the line https://github.com/darglein/ADOP/blob/main/src/README.md?plain=1#L31 that is not rendering as a step in the setup :roll_eyes: 
Maybe the bug report should be about that instead.

**Comment by darglein** [comment]
Oh thank you for finding that. Is the readme working now?

**Comment by Schwusch** [comment]
Now it's displaying as intended :) Nice job :+1:
