### ISSUE TITLE
Video rendering throw error when the image dimension is odd!

### ISSUE THREAD

**Issue by vahidEtt** [darglein/ADOP#21]
video rendering show the below error when one of image dimension is odd (render_scale is 1.0)

![gnome-shell-screenshot-JDWKC1](https://user-images.githubusercontent.com/75507961/141386965-f9d13c90-1bdc-4e9f-816b-197663ea9250.png)

**Comment by vahidEttehadi** [comment]
The problem came from the downscaling image by 2 for gt video. I simply disable it and now it's working.

**Comment by darglein** [comment]
Hello, I have updated the video recording code. 66e7812a926988f97bb905a99ee6b26cddf6cdc7

The video is now written frame by frame as .png images to the disk. It therefore should run without ffmpeg and handle all sizes.

**Comment by vahidEttehadi** [comment]
Great @darglein. Thanks!
