### ISSUE TITLE
Assertion 'idx != i' failed!

### ISSUE THREAD

**Issue by Lu-pin-an** [darglein/ADOP#24]
i use COLMAPY autoreconstruction my scene and run colmap2adop tool,after a long time i got:
 Loading initial PLY point cloud and preprocessing it (done only once)
Node  Trans: 0 0 0 1(almost 5 hours for 102MB .ply file)
Starting Build KDTree... Done in 2582.41ms.
Starting RemoveLonelyPoints...Assertion 'idx != i' failed!
  File: /home/lpa/ADOP/src/lib/data/SceneData.cpp:Assertion 'idx != i' failed!
  File: /home/lpa/ADOP/src/lib/data/SceneData.cpp:552
  Function: void SceneData::RemoveLonelyPoints(int, float)

**Comment by darglein** [comment]
Hey, ist that a public dataset and can you send me the point cloud so I can take a look?

If that's not possible you can uncomment the following lines in `SceneData.cpp`

```
        point_cloud.RemoveDoubles(0.0001);
        RemoveLonelyPoints(5, 0.02);
        RemoveClosePoints(0.00005);
```

**Comment by Lu-pin-an** [comment]
i have send my fused.ply file to your email,and i also try uncomment lines in SceneData.cpp,but it still get same problem.

**Comment by darglein** [comment]
I check the point cloud an it works for me. I think it is the same problem as #14 

Please pull the latest commit and also run a recursive submodule update. After that it should work fine.
