### ISSUE TITLE
Train on other scenes

### ISSUE THREAD

**Issue by Sylvia6** [darglein/ADOP#25]
Hi, thank you for the great project.
I noticed what you described in [Custom Datasets](https://github.com/darglein/ADOP/blob/main/scenes/README.md).
Here I have some questions about my dataset scenes.
1. Must  I use dataset generated by COLMAP? I have collected kitti dataset and processed their pose data into adop format and verified it.
2. But here remains something wrong with my point cloud file. I noticed that the input point cloud must have the info of positions, colors and normals, but in my kitti data I only have the position info. Can I initialize it with zero value mapped colors and zeros value mapped  normals?( colors = np.zeros(point.shape), normals = np.zeros(point.shape))
3. Furthermore, does the normal of point make a great role in adop function?
4. Can I use the normal calculated from range-view?

**Comment by darglein** [comment]
Hi, the normal is used to cull points that face away from the camera. If you have a scene with high depth complexity (indoor building with multiple rooms) this can help with the render quality.

I'm currently working on a functionality to use ADOP on scenes without a normal. Please check again in a few days.

to (4.) yeah, if you have the the capture location of each point you can just the difference.

**Comment by Sylvia6** [comment]
Thanks for your reply, it really makes sense to me!
