### ISSUE TITLE
The output of eval_mask and Groundtruth is abnormal

### ISSUE THREAD

**Issue by JOP-Lee** [darglein/ADOP#26]
Hi, thank you for your amazing work.
I tested it on the boat and multi_scene datasets you posted, and the results were good. However, some strange errors occurred when I tested other data sets. Groundtruth and eval_mask showed abnormal display. I checked many parameters and did not find the cause. The details are shown in the picture.
![image](https://user-images.githubusercontent.com/24960306/141949418-d5944749-1532-4171-9bca-3771041e7f5e.png)
![image](https://user-images.githubusercontent.com/24960306/141949382-3578b411-006c-43bb-843b-604b0d90b69f.png)

When I double-checked, I used the classmate's profile and code, and the results were still the same. But in his computer could get perfect results. The image size is 1241x376 and the image format is PNG. Is the question related to this? I feel very confused, Could you kindly find out what caused the problem?

**Comment by darglein** [comment]
Hi, is it possible that you share the scene folder with me? That would make finding the problem a lot easier :)

**Comment by JOP-Lee** [comment]
@darglein  Thank you for your help. I will send it to you by email.

**Comment by darglein** [comment]
Your dataset works fine on my system. This is the training output after 5 minutes:

![kitti](https://user-images.githubusercontent.com/16142878/141972505-ec10fa9c-40f5-48d3-9720-8093e1459343.gif)

If used the following parameter file:
```

[TrainParams]
random_seed = 3746934646
do_train = true
do_eval = true
batch_size = 1
inner_batch_size = 4
inner_sample_size = 3
num_epochs = 10
save_checkpoints_its = 10
eval_only_on_checkpoint = true
name = kitti_0_500_2
debug = false
output_file_type = .png
split_method = 
max_images = 4
duplicate_train_factor = 32
shuffle_initial_indices = false
shuffle_train_indices = true
split_remove_neighbors = 0
split_index_file_train = 
split_index_file_test = 
train_on_eval = true
train_factor = 0.0000000000
num_workers_train = 4
num_workers_eval = 2
train_crop_size = 256
train_mask_border = 16
reduced_check_point = true
write_images_at_checkpoint = true
keep_all_scenes_in_memory = false
use_image_masks = false
write_test_images = true
texture_random_init = true
texture_color_init = false
train_use_crop = true
experiment_dir = experiments/
scene_base_dir = scenes/
scene_names = kitt_data
checkpoint_directory = 
loss_vgg = 1.0000000000
loss_l1 = 1.0000000000
loss_mse = 0.0000000000
min_zoom = 0.7500000000
max_zoom = 1.5000000000
crop_prefere_border = true
optimize_eval_camera = false
interpolate_eval_settings = false
noise_pose_r = 0.0000000000
noise_pose_t = 0.0000000000
noise_intr_k = 0.0000000000
noise_intr_d = 0.0000000000
noise_point = 0.0000000000
lr_decay_factor = 0.7500000000
lr_decay_patience = 10
lock_camera_params_epochs = 50
lock_structure_params_epochs = 50


[RenderParams]
render_outliers = false
check_normal = true
ghost_gradients = true
drop_out_points_by_radius = true
outlier_count = 1000000
drop_out_radius_threshold = 0.6000000238
dropout = 0.2500000000
depth_accept = 0.0099999998
test_backward_mode = 0
distortion_gradient_factor = 0.0099999998
K_gradient_factor = 0.5000000000


[PipelineParams]
train = true
verbose_eval = false
log_render = false
log_texture = true
skip_neural_render_network = false
enable_environment_map = true
env_map_w = 1024
env_map_h = 512
env_map_channels = 4
num_texture_channels = 4
cat_env_to_color = false
cat_masks_to_color = false


[OptimizerParams]
texture_optimizer = adam
fix_render_network = false
fix_texture = false
fix_environment_map = false
fix_points = true
fix_poses = false
fix_intrinsics = true
fix_vignette = false
fix_response = false
fix_wb = true
fix_exposure = false
fix_motion_blur = true
fix_rolling_shutter = true
lr_render_network = 0.0004000000
lr_texture = 0.0100000000
lr_background_color = 0.0002000000
lr_environment_map = 0.0020000000
lr_points = 0.0001000000
lr_poses = 0.0050000000
lr_intrinsics = 0.0100000000
response_smoothness = 1.0000000000
lr_vignette = 0.0000050000
lr_response = 0.0010000000
lr_wb = 0.0010000000
lr_exposure = 0.0005000000
lr_motion_blur = 0.0050000000
lr_rolling_shutter = 0.0000020000


[NeuralCameraParams]
enable_vignette = true
enable_exposure = true
enable_response = true
enable_white_balance = false
enable_motion_blur = false
enable_rolling_shutter = false
response_params = 25
response_gamma = 0.4545454681
response_leak_factor = 0.0099999998


[MultiScaleUnet2dParams]
num_input_layers = 4
num_input_channels = 4
num_output_channels = 3
feature_factor = 4
num_layers = 4
add_input_to_filters = false
channels_last = false
half_float = false
upsample_mode = bilinear
norm_layer_down = id
norm_layer_up = id
last_act = 
conv_block = gated
conv_block_up = gated
pooling = average

```

**Comment by JOP-Lee** [comment]
@darglein  Thank you for your help. I also got the same result on my classmate's computer. I would like to ask what else might cause this problem in the case of the same code and data. For example, compilation problems or package saiga_OpenGL No?  I haven't started training yet. The output of GroudTruth image when eval epoch=0 is already an exception.

**Comment by darglein** [comment]
Can you try a full rebuild with a new conda environment? Maybe you have missed one of the changes in the last weeks.

**Comment by JOP-Lee** [comment]
@darglein thanks, i will try.

**Comment by Gatsby23** [comment]
> 

Sorry for troubling you. When you tranning this data, what have you done to the point cloud ? Are you rebuild the point cloud from all the lidar point from the different sequences and use the camera to color the point ?
