### ISSUE TITLE
[Question] running with custom images on pre-trained model

### ISSUE THREAD

**Issue by chris-aeviator** [darglein/ADOP#28]
Thanks for releasing ADOP. If I want to test ADOP on my own image dataset, I'll need to 

a) pre-process them with Colmap (do I need a dense reconstruction, a sparse reconstruction or just the camera poses?)
b) convert them to ADOP format via `colmap2adop`
c) load them into the `ADOP/scenes` folder

before running ADOP?

**Comment by darglein** [comment]
Hello,

a) You need both, the dense and sparse reconstruction. However from the dense reconstruction only the point cloud is required.

b) yes, also consider running `preprocess_point_cloud` after `colmap2adop`

c) This will automatically be done by `colmap2adop`.

After that run `adop_viewer` on you scene to check if the point cloud / poses are correct.

**Comment by chris-aeviator** [comment]
Thanks for the quick clarification.
