### ISSUE TITLE
Cmake runs to 100% but gets stuck on last file

### ISSUE THREAD

**Issue by PWhiddy** [darglein/ADOP#31]
Installation runs great up until the very end 
```[ 100%] Building CUDA object src/lib/CMakeFiles/NeuralPoints.dir/rendering/PointRenderer.cu.o```
where it will hang for at least 3 hours. Making no progress but uses a single core at 100% using only a tiny fraction of ram and no swap. A100 gpu, 12 cpu cores, debain.
Anyone else had this issue?

**Comment by PWhiddy** [comment]
Seemed the reason was that when I tried building, it selected my system cuda toolkit 11.3. My quick fix was just to rename my system cuda folder temporarily which caused the build to select the conda 11.2 version. Crazy that 11.2 works but 11.3 doesn't though!

**Comment by RobotBytedance** [comment]
> My quick fix was just to rename my system cuda folder temporarily which caused the build to select the conda 11.2 version. Crazy that 11.2 works but 11.3 doesn't though!

Sorry, I met the same problem as you. How to solve this ? Just change the folder name or reisntall cudatoolkit？
