### ISSUE TITLE
can this tool export the mesh and textures?

### ISSUE THREAD

**Issue by stjema** [darglein/ADOP#34]

**Comment by darglein** [comment]
No, because there exists no triangle mesh.

**Comment by stjema** [comment]
> No, because there exists no triangle mesh.

Huuuuuh? What is the model then made of? How can a mesh not have vertices? CONFUSION ATTACK!

**Comment by darglein** [comment]
It's a point cloud, which is also needed as an input so there would not be a reason to export it.

**Comment by stjema** [comment]
> It's a point cloud, which is also needed as an input so there would not be a reason to export it.

and why dont you want to make this tool a better alternative to photogrammetry tools?  3d artists want this tech.

**Comment by lukakostic** [comment]
> It's a point cloud, which is also needed as an input so there would not be a reason to export it.

So how could we export the point cloud?
3D scanning also exports point clouds which later turns into poligonal geometry.
