### ISSUE TITLE
Training stuck at 40% on epoch one

### ISSUE THREAD

**Issue by hammerchu** [darglein/ADOP#36]
![IMG_20211202_104320](https://user-images.githubusercontent.com/76043476/144351301-cbcfb1ea-b54e-4649-9a1e-8b06028010fc.jpg)

Hi, 

I am running the training of Boat example on a 12G RTX3060LHR which is a rather low end card compare to the hardware the model been tested with.
I managed to run training without dump core but the it stuck at around 40% at epoch 1 without improvement.

Setting i tried:
Inner batch size : 4 or 8
Batch size: 2
Train crop size: 256 or 128

**Comment by darglein** [comment]
Does the problem still persists with the latest patches?
