### ISSUE TITLE
unsupported GNU version! gcc versions later than 8 are not supported!

### ISSUE THREAD

**Issue by LinGeLin** [darglein/ADOP#37]
build follow src/README but error occured!
![image](https://user-images.githubusercontent.com/24861783/145418832-d0695aad-6a96-464b-aacc-1cc23f1f0174.png)

gcc=9.3,g++=9.3
ubuntu=20.04

**Comment by darglein** [comment]
It looks like the system CUDA is picked instead of the anaconda CUDA. You can verify that with `which nvcc`.

Did you set your `PATH` variable to a system CUDA installation?

**Comment by LinGeLin** [comment]
The version of conda may not be correct, so I failed to run create_environment.sh. `conda update conda` may be useful.

But in the end I reinstalled ubuntu18.04 instead of ubuntu20.04 and recompiled it using gcc-7.5
