### ISSUE TITLE
How to train with your own data?

### ISSUE THREAD

**Issue by AdamMarciniak** [darglein/ADOP#38]
What are the inputs for training? Say I go outside and want to do the same for new places or buldings/objects. Do I need to take a series of images or a video? How do I provide or get the initial pointcloud data?

Also, is there a way to train this on a GPU without the memory that you use? I've got a GTX 1070 Ti with like 8 GB of ram. Is there a setting I can use to make that work?

**Comment by darglein** [comment]
The basic pipeline would be:

1. Capture images
2. Reconstruct with COLMAP (sparse + dense)
3. Convert the colmap scene to adop
4. Train the system

8GB of video memory is quite low but if you reduce the batch size it should still work (quality might be a bit worse tho).

**Comment by yohannes-taye** [comment]
How to convert a colmap scene to adop? @darglein

**Comment by HandsomeFYM** [comment]
> How to convert a colmap scene to adop? @darglein

Maybe you will find the answer in this document.
The link: 
https://github.com/darglein/ADOP/blob/main/scenes/README.md
