### ISSUE TITLE
Is it possible to import generated scene in Unity or UnrealEngine VR app?

### ISSUE THREAD

**Issue by arty1901** [darglein/ADOP#53]
Im working on project for interaction with customs scenes for further analysis. And I want to upload generated model into my app to manipulate with it, if it`s possible.

**Comment by darglein** [comment]
That will be quite challenging, because you also need the ADOP rendering engine. Only exporting the point cloud will not help you very much. The color assigned to each point is a neural descriptor which cannot be interpreted by traditional renderers like Unity.
