### ISSUE TITLE
Strange random color when training

### ISSUE THREAD

**Issue by Sylvia6** [darglein/ADOP#55]
Hi，I have some doubt of my train result on other dataset.
It looks like below:( left picture is the train result, right is ground trurh)
![image](https://user-images.githubusercontent.com/32163681/157044515-7200aab5-9a86-4de3-a024-06ac6a38acc6.png)

I can not find out why it happens,  is it caused by the rasterization method?

Below show some of  the rasterization result:( left: train render result, medium: rgb ground truth, right:  rasterization mask)
![image](https://user-images.githubusercontent.com/32163681/157045090-647194a1-bf0a-4481-9386-0effe2bba693.png)

**Comment by darglein** [comment]
Can it be that these are spots that are not seen during training? So the color is uninitialized?

**Comment by Sylvia6** [comment]
@darglein  But it appears during the training time. I use the dense point cloud map collected from lidar. So some of the views have relatively sparse points, which means there might be more holes in a picture and might be filled with environment map sample texture. I wonder what causes the above abnormal phenomena.

**Comment by Gatsby23** [comment]
> @darglein But it appears during the training time. I use the dense point cloud map collected from lidar. So some of the views have relatively sparse points, which means there might be more holes in a picture and might be filled with environment map sample texture. I wonder what causes the above abnormal phenomena.

您好，我也尝试在自己的数据集上用ADOP进行训练，但有问题出来，可以加下您微信，跟您交流一下吗？

**Comment by Gatsby23** [comment]
> @darglein But it appears during the training time. I use the dense point cloud map collected from lidar. So some of the views have relatively sparse points, which means there might be more holes in a picture and might be filled with environment map sample texture. I wonder what causes the above abnormal phenomena.

Sorry for troubing you. I also have some problem when test the algorithm on lidar point cloud. I build the lidar point cloud densly. However, when I train the algorithm. There are a lot of black holes on the viewer GUI. I debug the point_cloud_initial, it still densely enough. I really don't know why
