### ISSUE TITLE
is the camera model not the real default in COLMAP? 

### ISSUE THREAD

**Issue by cduguet** [darglein/ADOP#58]
In the README, it says that (other than Fisheye) [the supported camera model is Pinhole/Distortion](https://github.com/darglein/ADOP/blob/3bcbbd6ca8b0069bfa6daf05143bee473b62d09e/README.md#camera-models) and that it's the same as the default in COLMAP. From what I see, it contains the distortion parameters [`(k1, k2, k3, k4, k5, k6, p1, p2)`](https://github.com/darglein/saiga/blob/master/src/saiga/vision/cameraModel/Distortion.h) in adition to the pinhole parameters [`(fx, fy, cx, cy, s)`](https://github.com/darglein/saiga/blob/9e9e7464eef8ada9b79f7d5f82be4e3d600acd05/src/saiga/vision/cameraModel/Intrinsics4.h#L16). The closest OpenCV equivalent for these parameters is [FullOpenCVCameraModel](https://github.com/colmap/colmap/blob/8bfff64843aea6c648ed7dfa5c28dd5b9d766b3b/src/base/camera_models.h#L279). However, [COLMAP uses SIMPLE_RADIAL as its default model](https://github.com/colmap/colmap/blob/e180948665b03c4a12d45e2ca39a589f42fdbda6/src/controllers/automatic_reconstruction.h#L72). SIMPLE_RADIAL only uses [`(f, cx, cy, k)`](https://github.com/colmap/colmap/blob/8bfff64843aea6c648ed7dfa5c28dd5b9d766b3b/src/base/camera_models.h#L214). It seems that Metashape also uses something [similar to the FullOpenCV model, with more tangential distortion only](https://www.agisoft.com/pdf/metashape-pro_1_5_en.pdf). 

Should I be safe to assume that you actually refer to a FullOpenCVCameraModel instead of a SimpleRadialCameraModel?

**Comment by darglein** [comment]
Hey, ADOP uses a more general Pinhole/Distortion model with 8 Parameters. It can be used for all of COLMAPS camera models. See here: https://github.com/darglein/saiga/blob/f3212a3ae8037ca23f69f1d6855fc889866c83e4/src/saiga/vision/util/ColmapReader.h

This is how you convert from COLMAP->ADOP


```
 case 1:
                {
                    // Pinhole
                    // fx, fy, cx, cy
                    std::array<double, 4> coeffs;
                    file >> coeffs;
                    c.K.fx = coeffs[0];
                    c.K.fy = coeffs[1];
                    c.K.cx = coeffs[2];
                    c.K.cy = coeffs[3];
                    break;
                }
                case 2:
                {
                    // Simple Radial
                    // f, cx, cy, k1
                    std::array<double, 4> coeffs;
                    file >> coeffs;
                    c.K.fx   = coeffs[0];
                    c.K.fy   = coeffs[0];
                    c.K.cx   = coeffs[1];
                    c.K.cy   = coeffs[2];
                    c.dis.k1 = coeffs[3];
                    break;
                }
                case 3:
                {
                    // RADIAL
                    // f, cx, cy, k1, k2
                    std::array<double, 5> coeffs;
                    file >> coeffs;
                    c.K.fx   = coeffs[0];
                    c.K.fy   = coeffs[0];
                    c.K.cx   = coeffs[1];
                    c.K.cy   = coeffs[2];
                    c.dis.k1 = coeffs[3];
                    c.dis.k2 = coeffs[4];
                    break;
                }
                case 4:
                {
                    // OPENCV
                    // fx, fy, cx, cy,   k1, k2, p1, p2
                    std::array<double, 8> coeffs;
                    file >> coeffs;
                    c.K.fx = coeffs[0];
                    c.K.fy = coeffs[1];
                    c.K.cx = coeffs[2];
                    c.K.cy = coeffs[3];

                    c.dis.k1 = coeffs[4];
                    c.dis.k2 = coeffs[5];
                    c.dis.p1 = coeffs[6];
                    c.dis.p2 = coeffs[7];
                    break;
                }

                case 6:
                {
                    // FULL_OPENCV
                    // fx, fy, cx, cy,   k1, k2, p1, p2,   k3, k4, k5, k6
                    std::array<double, 12> coeffs;
                    file >> coeffs;
                    c.K.fx = coeffs[0];
                    c.K.fy = coeffs[1];
                    c.K.cx = coeffs[2];
                    c.K.cy = coeffs[3];

                    c.dis.k1 = coeffs[4];
                    c.dis.k2 = coeffs[5];
                    c.dis.p1 = coeffs[6];
                    c.dis.p2 = coeffs[7];

                    c.dis.k3 = coeffs[8];
                    c.dis.k4 = coeffs[9];
                    c.dis.k5 = coeffs[10];
                    c.dis.k6 = coeffs[11];
                    break;
                };
```
