### ISSUE TITLE
Something wrong with the neural view using my own data

### ISSUE THREAD

**Issue by HandsomeFYM** [darglein/ADOP#71]
After using the ADOP viewer with 2 kinds of my trained data, I got the following results.
 
![2022-06-29 10-50-44 的屏幕截图](https://user-images.githubusercontent.com/36925916/176335060-ad41778e-311f-43f5-818d-abf305652d33.png)

![2022-06-29 11-08-36 的屏幕截图](https://user-images.githubusercontent.com/36925916/176336058-49e77c0e-94d2-4e9c-af05-e4d5a748f315.png)

All neural views of them are definitely wrong.
Is there the same problem with me?

By the way, when I used the ADOP viewer with the scene of "boat", there is a correct colored display in the neural view.

**Comment by darglein** [comment]
Did the training work? Does it output reasonable images?

**Comment by HandsomeFYM** [comment]
I think the training is working, there is no bug report.
The following is the training output
![2022-07-04 18-25-05 的屏幕截图](https://user-images.githubusercontent.com/36925916/177125778-af25b00b-7567-4b80-92bc-9e1341746474.png)

**Comment by darglein** [comment]
This is not the training output. By default it is written to the `experiments` dir.

**Comment by Gatsby23** [comment]
> After using the ADOP viewer with 2 kinds of my trained data, I got the following results.
> 
> ![2022-06-29 10-50-44 的屏幕截图](https://user-images.githubusercontent.com/36925916/176335060-ad41778e-311f-43f5-818d-abf305652d33.png)
> 
> ![2022-06-29 11-08-36 的屏幕截图](https://user-images.githubusercontent.com/36925916/176336058-49e77c0e-94d2-4e9c-af05-e4d5a748f315.png)
> 
> All neural views of them are definitely wrong. Is there the same problem with me?
> 
> By the way, when I used the ADOP viewer with the scene of "boat", there is a correct colored display in the neural view.

Have you solved your problem?

**Comment by HandsomeFYM** [comment]
Nope, I know something wrong with my training output, but I have no idea how to fix it.
And I am focused on other projects right now. Mabey I should close this issue.
