### ISSUE TITLE
failed to run the demo

### ISSUE THREAD

**Issue by zuixiaosanlang** [darglein/ADOP#73]
cd ADOP
./build/bin/adop_viewer --scene_dir scenes/boat

get
![image](https://user-images.githubusercontent.com/20105627/179454362-f224df3f-16b7-4107-9887-24850d73a42f.png)

[ 98%] Linking CXX executable ../../bin/preprocess_pointcloud
[ 98%] Built target preprocess_pointcloud
[ 98%] Linking CXX executable ../../bin/colmap2adop
[ 98%] Built target colmap2adop
[ 98%] Linking CXX executable ../../tests/test_loss
[ 98%] Built target test_loss
[100%] Linking CXX executable ../../bin/adop_viewer
[100%] Built target adop_viewer
[100%] Linking CXX executable ../../bin/adop_train
[100%] Built target adop_train
(adop) tesla@tesla-server:~/jyd/ADOP$ ./build/bin/adop_viewer --scene_dir scenes/boat
register neural render info
Git ref: 4c79a68c9111b3a05a9fe19816a699a79282f85a
Ref. 
=============== Saiga ===============
| Saiga Version     1.3.2           |
| Eigen Version     0.0.1           |
| Compiler          GNU             |
|   -> Version      7.5.0           |
| Build Type        RelWithDebInfo  |
| Debug             0               |
| Eigen Debug       1               |
| ASAN              0               |
| Asserts           1               |
| Optimizations     0               |
=====================================
Initializing GLFW.
Initializing GLFW sucessfull!
Creating GLFW Window. 1920x1080 Mode=3 Fullscreen=1 Borderless=0
=========================== OpenGL ===========================
| OpenGL Version    4.6 (Core Profile) Mesa 20.0.8           | 
| GLSL Version      4.60                                     | 
| Renderer          Mesa DRI Intel(R) UHD Graphics 630 (CFL GT2)| 
| Vendor            Intel Open Source Technology Center      | 
==============================================================
[Renderer] Target resized to 1920x1023
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/imgui_gl.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/tone_map.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/tone_map_linear.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_extract_bright.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_downsample.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_upsample.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_combine_simple.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/copy_image.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/compute_blur.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/compute_blur.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_directional.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_directional.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_point.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_point.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_spot.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_spot.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_point.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/light_spot.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/stenciltest.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/post_processing/post_processing.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/lighting/blitDepth.glsl
Deferred Renderer initialized. Render resolution: 1920x1023
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/post_processing/imagedisplay.glsl
Program Initialized!
Loading Scene scenes/boat
====================================
Scene Loaded
  Name       boat
  Path       /home/tesla/jyd/ADOP/scenes/boat
  Image Size 2880x1920
  Aspect     1.5
  K          2772.2 2775.23 1435.08 944.767 0 
  ocam       2880x1920 affine(1, 0, 0, 0, 0) cam2world() world2cam()
  ocam cut   1
  normalized center -0.00170931 -0.00793403 
  dist       -0.0756776 0.0746716 0 0 0 0 -0.000658676 -0.00050782 
  Points     53016216
  Colors     1
  Normals    1
  Avg. EV  14.7444
  Num Images 742
  Num Cameras 1
====================================
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/asset/ColoredAsset.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/asset/ColoredAsset.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/asset/ColoredAsset.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/asset/LineVertexColoredAsset.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/asset/LineVertexColoredAsset.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/asset/LineVertexColoredAsset.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/tone_map.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/tone_map_linear.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_extract_bright.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_downsample.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_upsample.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/bloom_combine_simple.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/copy_image.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/compute_blur.glsl
loading shader /home/tesla/jyd/ADOP/External/saiga/shader/compute/compute_blur.glsl
Found experiment experiments//2021-10-30_09:17:38_multi_scene_pose/ with 1 epochs
Found experiment experiments//2021-10-30_09:14:22_boat/ with 1 epochs
loading checkpoint 2021-10-30_09:14:22_boat -> ep0600
Using half_float inference
Load Checkpoint render
Total Model Params: 574651
GPU memory - Point Cloud: 1272.39MB
Pinhole Intrinsics:
Tensor [1, 13] float cuda:0 Min/Max -0.0756776 2775.23 Mean 609.79 Sum 7927.27 sdev 1060.86 req-grad 1
GPU memory - Texture: 848.259MB
Load Checkpoint points 53036216 max uv: 53036215
Load Checkpoint texture. Texels: 53036216 Channels: 4
Load Checkpoint pose
First pose before SE3(Quatwxyz(0.62515,-0.0614666,-0.771622,-0.100041),Vec3(2.91385,-0.583296,3.46712))
First pose after SE3(Quatwxyz(0.625108,-0.0614356,-0.771651,-0.100102),Vec3(2.91339,-0.583797,3.46737))
Load Checkpoint intrinsics
Load Checkpoint environment_map
Load Checkpoint vignette
Load Checkpoint response
Load Checkpoint exposures_values
Using Adam texture optimzier
optimizing texture with lr 0.01/0.0002
optimizing environment_map with lr 0.002
optimizing response with lr 0.001
optimizing vignette with lr 5e-06
optimizing poses with lr 0.005
Assertion 'cudaGraphicsGLRegisterImage(&graphic_resource, gl_buffer, gl_target, cudaGraphicsRegisterFlagsSurfaceLoadStore) == cudaSuccess' failed!
  File: /home/tesla/jyd/ADOP/External/saiga/src/saiga/cuda/interop.h:73
  Function: void Saiga::CUDA::Interop::initImage(unsigned int, gl::GLenum)
  Message: unknown error
已放弃 (核心已转储)
(adop) tesla@tesla-server:~/jyd/ADOP$

what is wrong, any suggest ？？？ thanks

**Comment by amoazeni75** [comment]
Hi,
I have the same issue.
Have you been able to solve it?

**Comment by zuixiaosanlang** [comment]
@amoazeni75 
i change the  driver  to NVIDIA-Linux-x86_64-470.129.06.run
