### ISSUE TITLE
doubt about the point cloud in demo video

### ISSUE THREAD

**Issue by zuixiaosanlang** [darglein/ADOP#76]
![image](https://user-images.githubusercontent.com/20105627/180359585-023405bc-8a23-485a-b16c-4fc7ca08d217.png)

in the video, the point cloud looks verg good. 
is it only comes from colmap?? 
not from Lidar ？？

**Comment by VisionaryMind** [comment]
@zuixiaosanlang, I have run this boat dataset through COLMAP, and this is definitely the result of dense reconstruction. This pipeline is not LIDAR-based. It requires cameras, poses, and corresponding points, which you would not be able to get with LIDAR alone.

**Comment by zuixiaosanlang** [comment]
@VisionaryMind 
hi, about the scene train, i use default colmap param, i just got 107356 points in sparse reconstruction；
but you got 217407 points. 
how to change the colmap param?? 
thanks

![image](https://user-images.githubusercontent.com/20105627/181161922-075379b4-ed12-44c2-a12a-d657a4868c0a.png)
![image](https://user-images.githubusercontent.com/20105627/181161933-9fc0f411-f45b-492a-94fb-0d58e5941c7c.png)

**Comment by VisionaryMind** [comment]
@zuixiaosanlang, to get that higher point count, you will need to run preprocess_pointcloud prior to training as follows:

`./build/bin/preprocess_pointcloud --scene_path scenes/your_scene_dir --point_factor 2`

I have tried 3 and 4, but this creates disturbances in the per-camera neural renders (blurring, color mismatches, etc.). Doubling the point count seems to be the best compromise for sparse camera sets.
