### ISSUE TITLE
poses.txt file missing

### ISSUE THREAD

**Issue by qiaosongwang** [darglein/ADOP#8]
Hi thanks for the awesome work!

I was trying to run ./bin/colmap2adop on my reconstruction, and pointed --sparse_dir --image_dir --point_cloud_file to the correct locations, but I still got the following error:

Assertion 'the pose file is required!' failed!
  File:  ADOP/src/lib/data/SceneData.cpp:125
  Function: SceneData::SceneData(std::string)
Aborted

I tried the given boat sample data, still same problem. Could you give more context on how to obtain the poses.txt file?

Thank you!

**Comment by darglein** [comment]
Please check if d18162163e8e2fa8a4f865b16d8a26f5a6549fe8 fixes your problem.

**Comment by gravicle** [comment]
that resolves it. Thank you @darglein

**Comment by qiaosongwang** [comment]
It works. Thanks @darglein!
