### ISSUE TITLE
`GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by amoazeni75** [darglein/ADOP#93]
I encountered the following error while I was trying to convert a custom dataset to ADOP compatible version using colmap2adop:

`.../envs/adop/lib/libstdc++.so.6: version GLIBCXX_3.4.30 not found`

Fix:
`conda activate adop`
`conda install -c conda-forge gcc=12.1.0`

**Comment by amoazeni75** [comment]
This shows us that the GCC versions (7 and 9) mentioned in the README file are incorrect. I hope others can save time ...

**Comment by lfranke** [comment]
Adding this here as well as a potential fix:
https://github.com/darglein/ADOP/issues/95#issuecomment-1924042405
